ES Modules (#295)
* Update package-lock.json file

* Fix broken tests in blank.spec.js

Blank binary file was not getting serialized as { type: "Buffer", data: [] }
because read(file) was returning a string instead of Buffer.

* Fix webpack error when running browser tests

Webpack 4 cannot parse module containing optional chaining operator.
See https://stackoverflow.com/questions/59972341/how-to-make-webpack-accept-optional-chaining-without-babel

* Fix tests in invalid.spec.js when running in Chrome

* Change statusCode to status

* Set the --openssl-legacy-provider flag when running browser tests

Recent versions of node upgraded to OpenSSL 3.0, which deprecated some
older crypto hashing algorithms including md4.

Webpack 4 hard codes the use of md4 ins some places, so we have to set this
flag until we can upgrade Webpack.

* Use isomorphic-fetch instead of node-fetch

Browser tests were failing as polyfill.js was loading a node package in a browser context.

* Increase minimum version of node to 17

This was when the --openssl-legacy-provider option was introduced.
Prior versions of node do not recognize this option.

* Add chokidar@3 as an explicit dev dependency

Browser tests are failing in the CI environment with:
chokidar@3: Error: Cannot find module 'chokidar'

Don't know why but this thread might be relevant:
https://github.com/facebook/create-react-app/issues/10811

* Skip test assertion due to conflict on Windows

See also https://github.com/APIDevTools/json-schema-ref-parser/pull/286

* Explicitly define browsers and plugins in karma.conf.js

* Replace karma-edge-launcher with newer package

* Increase default timeout of async tests

* Change package type to module

* Change require/module.exports to import/export in source files

* Delete "use strict" directives from source code

* Update tests to ES modules

* Re-export $RefParser methods as standalone functions

Preserve backwards compatibility

* Make karma config file a .cjs file

Fixes “require() of ES Module …/config.js not supported” error

* Avoid top-level await in path.js

The current configuration of karma uses Webpack 4, which can't parse
modules with top-level await.

* Revert back to __dirname for browser tests

Karma configuration needs to upgrade to Webpack 5 in order to use import.meta.url

* Fix lint issues

* Disable code coverage in CI for now

* Revert "Disable code coverage in CI for now"

This reverts commit f571f0a219c3e37f3f6745193b5595c61545bdd4.

* Replace nyc with c8 to work with ES modules

* Implement a dual CommonJS/ES module package.json

* Hack to allow $RefParser to be imported from require() without .default property

Without this hack, you would have to do this:

const $RefParser = require("@apidevtools/json-schema-ref-parser).default;

Now you can do this:

const $RefParser = require("@apidevtools/json-schema-ref-parser);