Fix CI tests (#294)
* Update package-lock.json file

* Fix broken tests in blank.spec.js

Blank binary file was not getting serialized as { type: "Buffer", data: [] }
because read(file) was returning a string instead of Buffer.

* Fix webpack error when running browser tests

Webpack 4 cannot parse module containing optional chaining operator.
See https://stackoverflow.com/questions/59972341/how-to-make-webpack-accept-optional-chaining-without-babel

* Fix tests in invalid.spec.js when running in Chrome

* Change statusCode to status

* Set the --openssl-legacy-provider flag when running browser tests

Recent versions of node upgraded to OpenSSL 3.0, which deprecated some
older crypto hashing algorithms including md4.

Webpack 4 hard codes the use of md4 ins some places, so we have to set this
flag until we can upgrade Webpack.

* Use isomorphic-fetch instead of node-fetch

Browser tests were failing as polyfill.js was loading a node package in a browser context.

* Increase minimum version of node to 17

This was when the --openssl-legacy-provider option was introduced.
Prior versions of node do not recognize this option.

* Add chokidar@3 as an explicit dev dependency

Browser tests are failing in the CI environment with:
chokidar@3: Error: Cannot find module 'chokidar'

Don't know why but this thread might be relevant:
https://github.com/facebook/create-react-app/issues/10811

* Skip test assertion due to conflict on Windows

See also https://github.com/APIDevTools/json-schema-ref-parser/pull/286

* Explicitly define browsers and plugins in karma.conf.js

* Replace karma-edge-launcher with newer package